Add mvc and actor`s page
frontend-park-mail-ru/2021_2_MAMBa pull request #11
Opened 2021-10-16 17:44 UTC by fillinmar

Архитектура MVC и страница актера

2021-10-20 20:35 UTC, Betchika99 commented on .gitignore
> +# pictures(пока нет бека)
так может мы удалим их, когда появится бек?)

2021-10-20 20:36 UTC, Betchika99 commented on public/components/actor/actor.scss
> +.actor-main{
пробел потерялся

2021-10-20 20:36 UTC, Betchika99 commented on public/components/actor/actor.scss
> +  margin-left: 12%;
выглядит, как костыль

2021-10-20 20:37 UTC, Betchika99 commented on public/components/actor/actor.scss
> +  padding: 250.11px 20.19px 28.86px 0;
костыль =(

2021-10-20 20:38 UTC, Betchika99 commented on public/components/collections/collections.scss
> +  width: 32.19%;
подгон =(

2021-10-20 20:40 UTC, Betchika99 commented on public/consts/urls.js
> +const deployUrl = 'https://film4u.club';
в идеале такие штуки не хардкодить, а в конфиге прописывать

2021-10-20 20:40 UTC, Betchika99 commented on public/css/consts.scss
> +$purple-button:#73324A;
сюда можно еще добавить шрифты и основные отступы (к примеру)

2021-10-20 20:41 UTC, Betchika99 commented on public/models/actorPage.js
> +            console.log(contentData);
логи убираем

2021-10-20 20:43 UTC, Betchika99 commented on public/models/actorPage.js
> +        getInfoAboutActor(actorId.id).then((contentData) => {
нейминг немного странный. actorId как будто уже айди, а ты у него еще айдишник берешь

2021-10-20 20:45 UTC, Betchika99 commented on public/models/homePage.js
> +    Promise.all([collections]).then((values) => {
а зачем делать all для одного промиса?

2021-10-20 20:46 UTC, Betchika99 commented on public/modules/adapters.js
> +    }
вообще этого можно не делать. Эта запись будет эквивалентна
```
{
       ... actorInfoJson.id,
        date: actorInfoJson.born + '   ·   ' + actorInfoJson.age,
}
```

2021-10-20 20:47 UTC, Betchika99 commented on public/modules/adapters.js
> +      date: actorInfoJson.born + '   ·   ' + actorInfoJson.age,
лучше использовать шаблонные строки

2021-10-20 20:47 UTC, Betchika99 commented on public/modules/adapters.js
> +export const arrayContentToActorPageContent = (actorInfoJson) => (
не очень понятное название для функции. В функции должен быть глагол

2021-10-21 15:33 UTC, fillinmar commented on public/models/homePage.js
> +    Promise.all([collections]).then((values) => {
не зачем)) исправила

2021-10-21 21:50 UTC, fillinmar commented on server/index.js
> +});
не нужно...

2021-10-31 11:47 UTC, Betchika99 requested changes
- [ ] вынести цвета в константы (чтобы была единая цветовая гамма сайта) и переехать на нее (где возможно)
- [x] не определять font-family там, где не нужно (где он наследуется)
- [ ] разобраться с импортами (где относительные, где-то абсолютные, лучше сделать одинаковыми)
- [ ] в JSDoc не должно быть типов с заглавной буквы. В джс все примитивные типы начинаются с маленькой. А с большой - это классы, что не совсем верно в нашем случае
- [ ] лучше писать комменты (JSDoc в частности) на одном языке :)
- [ ] убрать `bind`
- [ ] лишние шрифты лучше убрать, чтобы не нагружать сеть

ошибки писала не везде, поэтому лучше проверить их по всему проекту, чтобы я не повторялась :)

2021-10-31 11:47 UTC, Betchika99 commented on public/modules/http.js
> +    url: URLS.api.actor + actorId,
лучше использовать шаблонные строки

2021-10-31 11:47 UTC, Betchika99 commented on public/modules/http.js
> +    url: URLS.api.actorFilms + actorId+ '&skip='+ limit +'&limit='+skip,
лучше использовать шаблонные строки

2021-10-31 11:47 UTC, Betchika99 commented on public/modules/router.js
> +    this.application = app;
подсвечиваю еще раз

2021-10-31 11:47 UTC, Betchika99 commented on public/modules/router.js
> +    eventBus.on(Events.RedirectForward, this.forward.bind(this));
подсвечиваю еще раз

2021-10-31 11:47 UTC, Betchika99 commented on public/views/ActorView/ActorView.js
> +    buttonShowMore.addEventListener('click', () => {
на клики по кнопкам лучше на всякий случай делать `event.preventDefault`, чтобы можно было предотвратить случайное дефолтное поведение

2021-10-31 11:47 UTC, Betchika99 commented on public/views/ActorView/ActorView.js
> +      anchor.addEventListener('click', function(e) {
лучше стрелочную функцию

2021-10-31 11:47 UTC, Betchika99 commented on server/index.js
> +
может быть лучше все наши моковые данные, которые отдает этот сервер, вынести в отдельный файл здесь? чтобы в index.js только логика сервера осталась. а то очень длинный файл

2021-10-31 11:47 UTC, Betchika99 commented on webpack.config.js
> +};
этот файл очень похож на dev.config. Обычно такие повторы решают с помощью некоторого конфига webpack.common.config.js, и из него берут данные в dev и prod конфиги. Необязательно, но будет симпатичнее)

2021-10-31 19:53 UTC, fillinmar commented on public/components/actor/actor.scss
> +    &_pic-actor img {
однако, да, спасибо

2021-10-31 19:54 UTC, fillinmar commented on public/components/actor/actor.scss
> +          font-family: "Montserrat-Black", "Arial", sans-serif;
нет, этот шрифт только для имени актера, дефолтный regular

2021-10-31 21:27 UTC, fillinmar commented on public/consts/routes.js
> +  filmPage: '\\/film\\/\\d+',
хорошо, спасибо)

2021-10-31 21:29 UTC, fillinmar commented on public/controllers/actorController.js
> +export class ActorPagePageController extends BaseController {
ох, спасибо

2021-10-31 21:34 UTC, fillinmar commented on public/controllers/actorController.js
> +    this.eventBus.on(Events.ActorPage.Render.Content, this.view.renderContent);
осталось с прошлой версии, удалила, спасибо

2021-10-31 21:36 UTC, fillinmar commented on public/controllers/actorController.js
> +  }
точно, спасибо

2021-10-31 21:37 UTC, fillinmar commented on public/controllers/baseController.js
> +   */
ой, спасибо

2021-10-31 21:39 UTC, fillinmar commented on public/index.scss
> +.hidden{
спасибо

2021-10-31 21:44 UTC, fillinmar commented on webpack.config.js
> +};
хорошо) спасибо

2021-11-01 17:16 UTC, fillinmar commented on public/components/footer/footer.scss
> +  color:#5F5E5E;
макс подправит)

2021-11-01 17:16 UTC, fillinmar commented on public/components/footer/footer.scss
> +}
макс подправит)

2021-11-01 17:17 UTC, fillinmar commented on public/consts/events.js
> +export const Events = {
в последствии переименуем, а то много ошибок сейчас будет у нас с максом

2021-11-01 17:17 UTC, fillinmar commented on public/consts/routes.js
> +export const Routes = {
в последствии переименуем, а то много ошибок сейчас будет у нас с максом

2021-11-01 17:19 UTC, fillinmar commented on public/consts/urls.js
> +    actor: `${currentUrl}/api/actor/getActor/skipPopular=0&limitPopular=11&skipFull=0&limitFull=3&id=`,
в конце айдишник актера, константы вынесу, спасибо.

2021-11-02 07:31 UTC, fillinmar commented on public/modules/http.js
> +    url: URLS.api.actor + actorId,
thanks

2021-11-02 08:50 UTC, fillinmar commented on public/modules/adapters.js
> +  }, []);
исправила на map)

2021-11-05 11:52 UTC, Betchika99 requested changes

2021-11-05 11:52 UTC, Betchika99 commented on public/models/actorModel.js
> +    if (actor === undefined || actor.id === undefined) {
обычно так не проверяют. К тому, что в actor может быть не только undefined. Лучше проверять так (более универсально):
`if (!actor?.id) {`

здесь и далее

2021-11-05 12:29 UTC, merged