Building auth and fixing header
frontend-park-mail-ru/2021_2_MAMBa pull request #14
Opened 2021-10-30 21:13 UTC by maksongold

2021-10-31 21:42 UTC, Betchika99 requested changes
- [ ] использовать вложенность в scss
- [x] при получении полей объектов лучше валидировать, что поле существует, чтобы не было потенциальной JS-ошибки и краша страницы (можно использовать optional chaining)
- [x] избавиться от лишней вложенности объектов, где возможно
- [x] избавиться от лишней вложенности if-операторов, где возможно
- [x] синхронизировать с Мариной названия методов в http-модуле, чтобы они были в одном стиле
- [ ] по возможности добавить JSDoc к функциям и методам классов
- [ ] прогнать линтер

2021-10-31 21:42 UTC, Betchika99 commented on public/models/authModel.js
> +    if (routeData.path.path === Routes.AuthPage) {
а почему двойная вложенность `path` в `routeData`? нельзя ограничиться одной? если оставлять так, то нужна доп проверка, что `routerData.path` существует, иначе может быть ошибка

2021-10-31 21:42 UTC, Betchika99 commented on public/models/authModel.js
> +    eventBus.emit(Events.PathChanged, '/');
вместо '/' лучше использовать константу из путей

2021-10-31 21:42 UTC, Betchika99 commented on public/models/authModel.js
> +    for (const input in AuthConfig) {
обычно внутри for использует let, а не const , чтобы не плодить ячейки памяти на каждой итерации, а переиспользовать

2021-10-31 21:42 UTC, Betchika99 commented on public/models/authModel.js
> +      if (error.regexp === undefined) {
лучше проверять на `!error.regex` или `typeof error.regex === 'undefined'`

2021-10-31 21:42 UTC, Betchika99 commented on public/models/authModel.js
> +          if (inputValue !== passwordValue) {
зачем нужна такая вложенность? почему не объединить условия через && ?

2021-10-31 21:42 UTC, Betchika99 commented on public/models/authModel.js
> +    if (!hasErrorInputs) {
лучше написать `if (hasErrorInputs) return`, а дальнейший блок вынести из условия

2021-10-31 21:42 UTC, Betchika99 commented on public/models/authModel.js
> +        login(inputsData).then((response) => {
у всех промисов лучше обрабатывать `.catch`

2021-10-31 21:42 UTC, Betchika99 commented on public/models/authModel.js
> +          if (response.status === 200) {
разве регистрация не 201 возвращает?

2021-10-31 21:42 UTC, Betchika99 commented on public/models/header.js
> +    this.eventBus.emit(Events.Header.ChangeActiveButton, null);
можно не передавать null, там по умолчанию будет пустая дата (undefined)

2021-10-31 21:42 UTC, Betchika99 commented on public/models/header.js
> +    }
мне кажется, это не очень эффективный алгоритм. Можно через `find` найти в `headerLinks.headerLinks` нужный `link.href` и для него вызвать `emit`. Или проверить наличие нужного `path` в `headerLinks.headerLinks` и если есть, то эмитнуть с path

2021-10-31 21:42 UTC, Betchika99 commented on public/models/header.js
> +    for (const link of headerLinks.headerLinks) {
зачем лишняя вложенность для `headerLinks`?

2021-10-31 21:42 UTC, Betchika99 commented on public/models/model.js
> +export class Model {
может ее лучше назвать BaseModal? по аналогии с контроллерами?

2021-10-31 21:42 UTC, Betchika99 commented on public/modules/authorization.js
> +    // TODO fetch to server /logoutUser
сейчас нет ручки на логаут?

2021-10-31 21:42 UTC, Betchika99 commented on public/modules/authorization.js
> +        const id = response.parsedJson.body.id;
лучше обложить проверками существование полей в каждом из объектов

2021-10-31 21:42 UTC, Betchika99 commented on public/modules/authorization.js
> +        const id = response.parsedJson.body.id;
а еще здесь можно использовать деструктуризацию

2021-10-31 21:42 UTC, Betchika99 commented on public/modules/authorization.js
> +          getCurrentUser(id).then((response) => {
а зачем делать дополнительный запрос здесь?

2021-10-31 21:42 UTC, Betchika99 commented on public/modules/http.js
> +    url: URLS.api.getUser + id,
лучше использовать конкатенацию

2021-10-31 21:42 UTC, Betchika99 commented on public/modules/router.js
> +    this.application.addEventListener('click', (e) => {
нужно проверить, что this.application существует

2021-10-31 21:42 UTC, Betchika99 commented on public/views/ActorView/ActorView.js
> +      for (const anchor of anchors) {
было лучше :)

2021-10-31 21:42 UTC, Betchika99 commented on public/views/AuthView/AuthView.js
> +// TODO CHANGE SUBMIT BUTTON AFTER CLICK OR INSERT LOADER
а почему сразу не сделано?

2021-10-31 21:42 UTC, Betchika99 commented on public/views/HeaderView/HeaderView.js
> +    if (buttonHref === null) {
лучше проверить на `!buttonHref`

2021-10-31 22:13 UTC, maksongold commented on public/consts/header.js
> +      href: '/actor/1',
Не моё

2021-10-31 22:15 UTC, maksongold commented on public/consts/validateErrors.js
> +    {text: 'Введены небуквенные символы или их длина меньше 2 или больше 30!', regexp: /^[^0-9_!.,\-¡?÷¿/\\+=@#$%ˆ&*(){}| ~<>;:[\]]{2,30}$/},
Я не знаю как, если бы ты привела пример было бы круто

2021-10-31 22:16 UTC, maksongold commented on public/controllers/authController.js
> +    this.eventBus.on(Events.Authorization.GotUser, this.model.redirectToHomePage);
Да, видел так и сделаем

2021-10-31 22:17 UTC, maksongold commented on public/main.js
> +const AuthModule = authModule;
Для инициализации

2021-10-31 22:17 UTC, maksongold commented on public/models/authModel.js
> +    if (routeData.path.path === Routes.AuthPage) {
Это объект для пага, поэтому двойная вложенность, проверку сделаю

2021-10-31 22:18 UTC, maksongold commented on public/models/authModel.js
> +    for (const input in AuthConfig) {
Линтер ругается кстате

2021-10-31 22:22 UTC, maksongold commented on public/modules/authorization.js
> +          getCurrentUser(id).then((response) => {
Бэкэнд

2021-11-04 12:04 UTC, maksongold commented on public/views/ActorView/ActorView.js
> +      for (const anchor of anchors) {
не моё

2021-11-04 13:41 UTC, maksongold commented on public/modules/authorization.js
> +        const id = response.parsedJson.body.id;
> а еще здесь можно использовать деструктуризацию

не понял

2021-11-09 18:26 UTC, merged