Add film page and reviews mb_cd0
frontend-park-mail-ru/2021_2_MAMBa pull request #15
Opened 2021-10-31 13:43 UTC by fillinmar

2021-11-07 15:16 UTC, Betchika99 requested changes
- [ ] убрать хардкод для перехода на страницы фильма и актера
- [ ] прогнать линтер
- [ ] добавить babel-конфиг

2021-11-07 15:16 UTC, Betchika99 commented on public/views/FilmView/FilmView.js
> +  }
если тебе нужно просто навесить класс при ховере, лучше использовать псевдокласс `:hover` в css

2021-11-07 15:16 UTC, Betchika99 commented on public/views/FilmView/FilmView.js
> +      document.getElementById('input').value = '';
нужно проверить, что элемент найден, прежде, чем что-то присваивать

2021-11-07 15:16 UTC, Betchika99 commented on public/views/FilmView/FilmView.js
> +      const textInput = document.querySelector('.write_review__text').value;
нужно проверить, что элемент найден, прежде, чем что-то присваивать

2021-11-07 15:16 UTC, Betchika99 commented on public/views/FilmView/FilmView.js
> +    if (className === undefined) {
не проверяем так на `undefined` :)

2021-11-07 15:16 UTC, Betchika99 commented on public/consts/header.js
> +    },
а почему это в шапке? или почему это хардкод?

2021-11-07 18:33 UTC, fillinmar commented on public/models/actorModel.js
> +    if (!actor?.id && !actor?.limit && !actor?.limit) {
мне все поля нужны, чтоб подгрузить фильмы

2021-11-07 18:34 UTC, fillinmar commented on public/models/filmModel.js
> +        // TODO изменить рейтинг фильма
как пользователь поставит оценку, итоговый рейтинг фильма измениться, поэтому надо отобразить новый рейтинг

2021-11-07 18:43 UTC, fillinmar commented on public/views/FilmView/FilmView.js
> +        };
потому что мне надо передать в паг переменную, а для этого надо создать объект

2021-11-07 18:53 UTC, fillinmar commented on public/consts/header.js
> +    },
уберем, как появятся коллекции

2021-11-07 19:01 UTC, fillinmar commented on public/modules/adapters.js
> +  };
да, спасибо

2021-11-07 19:08 UTC, fillinmar commented on public/modules/adapters.js
> +    const actors = {};
умно, спасибо))

2021-11-07 19:30 UTC, fillinmar commented on public/modules/adapters.js
> +  }, []);
умно))

2021-11-08 09:20 UTC, fillinmar commented on public/views/FilmView/FilmView.js
> +    if (className === undefined) {
ой

2021-11-10 10:02 UTC, closed without merging