Auth log layout mb d3fe3
frontend-park-mail-ru/2021_2_MAMBa pull request #3
Opened 2021-09-26 16:50 UTC by maksongold

2021-09-26 20:02 UTC, Betchika99 requested changes
Неплохо, но можно лучше :)
- [x]  пройтись по коду aka линтер. Лучше, когда ты сам видишь проблемы и их фиксишь. В этом помогают настройки IDE
- [ ] айдишники в качестве идентификаторов в современном вебе редко используют, лучше классы
- [x] есть общие ошибки: let/const, дефолтный экспорт, пустая строка в конце файла, кавычки. Лучше это везде поправить, я не везде это писала
- [ ] зачем так много шрифтов прикреплено? в коде видела только один шрифт

2021-09-26 20:02 UTC, Betchika99 commented on public/utils/ajax.js
> +    };
такие штуки лучше выносить в константы в отдельном файле

2021-09-26 20:02 UTC, Betchika99 commented on public/main.js
> +        Ajax.ajaxPost({
лучше использовать методы с fetch

2021-09-28 10:11 UTC, maksongold commented on public/components/footer/footer.js
> +    return template;
на будущее заготовочка

2021-09-28 10:15 UTC, maksongold commented on public/main.js
> +    root.innerHTML = '<h1>SUCCESS</h1>';
просто чтоб что то было

2021-09-28 10:16 UTC, maksongold commented on public/modules/utils.js
> +    return temp.firstChild;
лишний div

2021-09-28 10:18 UTC, maksongold commented on public/modules/utils.js
> +}
мне ж не все стили нужны а только определенных элементов

2021-09-28 10:18 UTC, maksongold commented on public/static/fonts/OFL.txt
> +Copyright 2011 The Montserrat Project Authors (https://github.com/JulietaUla/Montserrat)
упс

2021-09-28 10:20 UTC, maksongold commented on server/server.js
> +        return res.status(400).json({error: 'Не валидные данные пользователя'});
код с лекции эт не я 😁

2021-09-28 14:16 UTC, Betchika99 approved these changes

2021-09-29 09:49 UTC, merged